FROM python:3.10-slim 

WORKDIR /opt/bot

COPY imoex_bot.py .
COPY requirements.txt .
COPY utils ./utils/

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install python-telegram-bot==20.3  # Явно указываем версию

RUN useradd -m botuser && \
    chown -R botuser:botuser /opt/bot
USER botuser

CMD ["python", "imoex_bot.py"]